# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

version: "3.8"
   
services:
    server:
        build: .
        container_name: python_server
        command: python real_estate.py 
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres:latest
        container_name: pgdb
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        # speciefies where the volumne is placed or connected to in the container
        volumes:
            - pgdata:/var/lib/postgressql/data/
# stores data in our host
volumes:
    pgdata: